### PR TITLE
fix: Presenter screen not working

### PR DESCRIPTION
**Pull request by jstarpl**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Bug fix

* **What is the current behavior?** (You can also link to an open issue here)

Displaying the Presenter screen in CasparCG results in the following:

```
[2021-02-18 15:33:23.469] [13304] [error]   html[https://[sofie]/countdowns/studio0/presenter] Log: Uncaught TypeError: Promise.allSettled is not a function
[2021-02-18 15:33:23.470] [13304] [error]   html[https://[sofie]/countdowns/studio0/presenter] Log: Uncaught TypeError: Cannot destructure property `ServiceConfiguration` of 'undefined' or 'null'.
```

* **What is the new behavior (if this is a feature change)?**

A shim is included to emulate the behavior of `Promise.allSettled` in browser that don't support it (like Chromium in CasparCG 2.1.12).

* **Other information**:

**Status**

- [ ] Code documentation for the relevant parts in the code have been added/updated by the PR author
- [ ] The functionality has been tested by the PR author
- [ ] The functionality has been tested by NRK

### CODE REVIEW

**Review by sparkpunkd — APPROVED** [review]
Good spot and thanks for the good comment to to explain the reason for the polyfill in this context.

**Comment by Julusian** [comment]
I feel like this polyfill should not be necessary.
Meteor produces two client bundles, one for modern browsers and one for legacy, so either casparcg chromium is choosing the wrong one, or the legacy bundling is bad

**Comment by jstarpl** [comment]
@Julusian I think it's possible that Meteor considers CasparCG's browser "modern enough": https://docs.meteor.com/changelog.html#changes-23 - this seems to indicate that the switch is based on a browser version number, not a particular feature set. On the other hand, forcing CasparCG to use legacy bundle, when 99,9% of the "modern" code will work is harsh and may impact performance of the code running in the CasparCG renderer.

**Comment by Julusian** [comment]
@jstarpl yeah, but I would expect meteor to be transpiling the very new features for older 'modern' browsers. They say the cut off is async/await support, but allSettled is a much more recent addition.

Either way, I don't object to this, Im just curious as to how it became a problem

**Pull request merged**
