### PR TITLE
Maintenance/no focused test linting

### PR DESCRIPTION
**Pull request by gundelsby**
* **What kind of change does this PR introduce?** enforces a linting rule that disallows committing test files which includes focused tests. This hinders accidentally disabling all our tests but one.

* **What is the current behavior?** You are allowed to commit code that disables all tests but one.

**Status**
- [X] The functionality has been tested by the PR author
- [ ] The functionality has been tested by NRK

### CODE REVIEW

**Comment by Julusian** [comment]
Has this rule been customised to detect uses of `testInFiberOnly`?

**Comment by gundelsby** [comment]
> 
> 
> Has this rule been customised to detect uses of `testInFiberOnly`?

No, it's just the one line ignore. So I guess you can circumvent this safeguard by calling that function. Not entirely sure what to do about it, if anything. Adding the linting rule makes is less likely to disable the tests, but not entirely impossible.

**Comment by Julusian** [comment]
hmm yeah this isnt even configurable to add that.
that makes the value of using this in this repo questionable, as most of the tests use testInFiber, so would need to use testInFiberOnly instead of test.only

**Comment by nytamin** [comment]
converting this back into a draft, while you guys look for a more appropriate solution

**Comment by Julusian** [comment]
I spent the 15 minutes this morning to do this.
Its a simple copy of the rule, with the regex changed

**Comment by Julusian** [comment]
Manually merged in 24fa60c172d48707b61da2b386b731cf62a84849
This was causing some weird typings issues that went away with discarding the large package-lock changes

**Pull request closed without merging**
