### PR TITLE
Feat/nrcs name

### PR DESCRIPTION
**Pull request by thomasslee97**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This adds the meteor/core setting `nrcsName` which allows the changing of text containing "ENPS" or "MOS" to the name of other systems e.g. "iNews". The default name is "ENPS". This is an intermediary step to allow easy customization, in the future a better approach would be for ingest gateways to report the names to use.

**Status**

- [X] The functionality has been tested by the PR author
- [ ] The functionality has been tested by NRK

### CODE REVIEW

**Comment by Julusian** [comment]
This might be better to do with a setting on the studio rather than a system setting?
I can see it being possible in future for an installation to want to use different ingest methods for different studios
What do you think @nytamin?

**Comment by nytamin** [comment]
Yes, ideally it should come from the Gateway (that talks to the NCS) somehow, but I could be ok with a temporary solution of having it in on a Studio.

**Comment by nytamin** [comment]
Following a discussion with @jesperstarkar, I looked into an alternative approach where the NRCS name is stored on the rundown instead.

It's more or less done, although I need to confer with @jstarpl and test it before it can be considered done:
https://github.com/nrkno/tv-automation-server-core/compare/release23...olzzon:feat/nrcs-name-rundown

**Comment by thomasslee97** [comment]
@nytamin you may need to apply the same fix as https://github.com/nrkno/tv-automation-server-core/pull/288/commits/11e80cd7d6bd454af8e4e6490bf0877b30b80a9a a comma was in the wrong place

**Comment by jstarpl** [comment]
> 
> 
> Following a discussion with @jesperstarkar, I looked into an alternative approach where the NRCS name is stored on the rundown instead.
> 
> It's more or less done, although I need to confer with @jstarpl and test it before it can be considered done:
> [release23...olzzon:feat/nrcs-name-rundown](https://github.com/nrkno/tv-automation-server-core/compare/release23...olzzon:feat/nrcs-name-rundown)

Yeah, I think I like that approach much better. This way, it can come straight from the gateway, a single studio can (potentially) use multiple NRCS/rundown sources. I think that way makes much more sense than a system- or studio-wide config.

**Comment by jstarpl** [comment]
Since @nytamin has already implemented it, I would be for forgoing this intermediate step and go straight to the solution: https://github.com/nrkno/tv-automation-server-core/pull/298 . Adding this information is not an extreme burden on the gateways, and allows much cleaner implementation.

**Comment by nytamin** [comment]
closing this in favor of #298

**Pull request closed without merging**
