### PR TITLE
fix: ensure that the piece is actually playing in sourceLayerOnPartStop

### PR DESCRIPTION
**Pull request by jstarpl**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Before, sourceLayerOnPartStop would stop all pieces that it could find on a given source layer. The expected behavior is to stop only the currently playing pieces.

* **What is the current behavior?** (You can also link to an open issue here)

All pieces on a given source layer are stopped. As a result, pieces with effective negative length (with enable: X, and userDuration.end: Y, X > Y) would be set.

* **What is the new behavior (if this is a feature change)?**

The method filters the enable.start value to only mutate pieces that should be currently playing. The filtering is done at the `ServerPlayoutAPI.sourceLayerOnPartStop` to leave the underlying `ServerPlayoutAdLibAPI.innerStopPieces` functionality unaffected.

* **Other information**:

**Status**

- [x] The functionality has been tested by the PR author
- [ ] The functionality has been tested by NRK

### CODE REVIEW

**Review by Julusian — CHANGES_REQUESTED** [review]
Good spot
I think it would be better to do the check inside of `ServerPlayoutAdLibAPI.innerStopPieces` though, otherwise adlib-actions will still make a mess

It turns out tv2 also did a similar fix that didnt made it into a pr https://github.com/olzzon/tv-automation-server-core/commit/284b59ea67657911d5322008837dc189024d86a8

I am happy with their fix, so we could cherry-pick that in instead?

**Comment by thomasslee97** [comment]
If you pull in that commit you will also want https://github.com/olzzon/tv-automation-server-core/commit/da0b290434e7479645f54904a6cf7991b31a6b4b

**Comment by jstarpl** [comment]
> 
> 
> Good spot
> I think it would be better to do the check inside of `ServerPlayoutAdLibAPI.innerStopPieces` though, otherwise adlib-actions will still make a mess
> 
> It turns out tv2 also did a similar fix that didnt made it into a pr [olzzon@284b59e](https://github.com/olzzon/tv-automation-server-core/commit/284b59ea67657911d5322008837dc189024d86a8)
> 
> I am happy with their fix, so we could cherry-pick that in instead?

👍  Let's make a PR out of those two commits then.

**Comment by jstarpl** [comment]
Replaced with: https://github.com/nrkno/tv-automation-server-core/pull/338

**Pull request closed without merging**
