### PR TITLE
fix: Migration for stk&full audio remapping

### PR DESCRIPTION
**Pull request by jesperstarkar**
Adds a missing commit from R4 to master.

The current 18.1 on master is missing this commit.

### CODE REVIEW

**Comment by jesperstarkar** [comment]
Also, the git tree becomes much cleaner by merging this.

**Comment by Julusian** [comment]
This wasn't merged as in R5 the migration is in the blueprints instead. 
Part of https://github.com/nrkno/tv-automation-sofie-blueprints/commit/afd067d62739cd49318cf20d2dad0d2de1c121c6

**Comment by jesperstarkar** [comment]
So this is invalid and should be closed?

**Comment by Julusian** [comment]
I didn't realise this was to master and not develop. it probably should be merged to master

**Comment by jesperstarkar** [comment]
Yeah, it is to actually release R4, which we haven't fully done

**Pull request merged**
