### PR TITLE
Feat/improve nrcs unsync notification

### PR DESCRIPTION
**Pull request by gundelsby**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Improved wording for user notifications when rundowns are unsynced from the NRCS.

**Status**

- [X] Code documentation for the relevant parts in the code have been added/updated by the PR author
- [X] The functionality has been tested by the PR author
- [ ] The functionality has been tested by NRK

### CODE REVIEW

**Comment by gundelsby** [comment]
@jstarpl I updated i18next-scanner to get a newer acorn version (that handles .? optionals better) and changed the configuration to set a higher ecma version, figured I'd let you do a sanity check

@tsorbo QA på oversettelsene, vennligst :)

**Review by jstarpl — APPROVED** [review]
Nice that you've updated the Acorn version, I remember the lack of support of new operators was a problem in a couple of places, but no update was available back then.

**Comment by gundelsby** [comment]
> 
> 
> Nice that you've updated the Acorn version, I remember the lack of support of new operators was a problem in a couple of places, but no update was available back then.

There are still a couple of error messages when extracting, but the keys seem to be extracted nonetheless. So I guess it's... fine? 😏

**Comment by gundelsby** [comment]
Terje will do a major overhaul of the translations shortly, so I'll just merge for now.

**Pull request merged**
