### PR TITLE
Automatic formatting test #1

### PR DESCRIPTION
**Pull request by gundelsby**

### CODE REVIEW

**Comment by gundelsby** [comment]
At this point (f228dc138abbb38fd248bf269f7f4b4fe93d78e2), all test suites fail.

**Comment by gundelsby** [comment]
Tests pass now, unsure why the coverage has gone down 🤔

**Comment by Julusian** [comment]
Coverage decreasing makes sense to me as this increases the linecount by 23000.
It is likely because of all the throws that were written on the same line as an if statement

**Comment by gundelsby** [comment]
> 
> 
> Coverage decreasing makes sense to me as this increases the linecount by 23000.
> It is likely because of all the throws that were written on the same line as an if statement

Yeah, that makes sense. Good thinking :)

**Comment by gundelsby** [comment]
Closing this, created another branch for testing which is based on a newer version of master.

**Pull request closed without merging**
