### PR TITLE
feat: Service messages

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jstarpl** [comment]
I'm merging this into develop, as this feature seems finished and should be included in R13

**Comment by nytamin** [comment]
Oh, I had some things I would've liked to be changed first. I had a call planned with Ola, but other things got in the way the last week..

**Comment by jstarpl** [comment]
Ha, ok, that's unfortunate. I didn't see any movement on this for a month now and Ola moved onto other things so I thought that it was just left behind and something we forgot. Do you want me to revert it and undelete the branch then?

**Comment by nytamin** [comment]
Nah, I'll have a talk with him about it and we'll perhaps patch /develop later.

**Pull request merged**
