### PR TITLE
chore: fix pre-commit script to work on Linux and macOS

### PR DESCRIPTION
**Pull request by ianshade**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Pre-commit script fix

* **What is the current behavior?** (You can also link to an open issue here)
Failing on Linux and macOS.

* **What is the new behavior (if this is a feature change)?**
Use $OSTYPE to detect the OS.
Force meteor to run in x86 on ARM Macs. (to be removed when upgrading to meteor that supports arm64) 

* **Other information**:
Tested only on Windows and macOS, not tested on Linux.

**Status**

- [ ] Code documentation for the relevant parts in the code have been added/updated by the PR author
- [ ] The functionality has been tested by the PR author
- [ ] The functionality has been tested by NRK

### CODE REVIEW

**Comment by nytamin** [comment]
To the reviewers: plz comment below with which platforms you have tested this on

- [ ]  Windows
- [ ] MacOS
- [ ] Linux

**Comment by Julusian** [comment]
Not working on linux 
image

**Comment by ianshade** [comment]
TIL that [[ is a bash thing, not a POSIX standard. And bash is not the default shell on Ubuntu. I chose to stick to the default shell and use a different method of comparing strings.

**Comment by Julusian** [comment]
It works on linux now

**Review by nytamin — APPROVED** [review]
Works on Windows 👍

**Pull request merged**
