### PR TITLE
feat: Route Set UI 2

### PR DESCRIPTION
**Pull request by jstarpl**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

This PR introduces a new UI for the Route Sets.

* **What is the current behavior?** (You can also link to an open issue here)

The UI for the Route Sets consists of a couple of buttons in the sidebar in Rundown View and a modal confirmation box for enabling/disabling.

* **What is the new behavior (if this is a feature change)?**

All of the controls are combined into a panel, next to the support panel, with buttons to toggle the routes on and off.

* **Other information**:

The Studio has a new map that allows specifying properties for the exclusivity groups. Currently, it's just user-facing labels.

**Status**

- [x] The functionality has been tested by the PR author
- [ ] The functionality has been tested by NRK

### CODE REVIEW

**Comment by nytamin** [comment]
When there are exactly 2 RouteSets in an exclusivity group, they should turn into a single selector:
image

vs

image

**Comment by nytamin** [comment]
Another note:
Could you flip the toggles, so that "on" is to the right, instead of left?
(I asked Jonas to flip the design sketches as well)

image

**Review by nytamin — CHANGES_REQUESTED** [review]
I've read through the code and code-wise it looks all good!

I put some remarks on the GUI functionality as separate comments though.

**Comment by jstarpl** [comment]
> When there are exactly 2 RouteSets in an exclusivity group, they should turn into a single selector:
> image
> image

The 2 RouteSets in a single exclusivity group combined into one kicks in if both of those route-sets are set as "activate-only".

**Comment by jstarpl** [comment]
> 
> 
> Another note:
> Could you flip the toggles, so that "on" is to the right, instead of left?
> (I asked Jonas to flip the design sketches as well)
> 
> image

I've flipped the labels.

**Review by nytamin — APPROVED** [review]
Looks good!

**Pull request merged**
