### PR TITLE
Feat: Pad piece start when created by action

### PR DESCRIPTION
**Pull request by thomasslee97**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This aims to change the behavior of the adLib action function `insertPiece` such that when you insert a piece into the currently playing part, it is inserted relative to the playhead position rather than the start of the part. i.e. a piece with `start: 0, end: 10` would become `start: 0 + playhead, end: 10 + playhead`.

* **Other information**:
Perhaps this should be behind a flag like `insertAtPlayhead: boolean`?

**Status**

- [X] The functionality has been tested by the PR author
- [ ] The functionality has been tested by NRK

### CODE REVIEW

**Comment by jstarpl** [comment]
Why not just use start: 'now'?

**Comment by Julusian** [comment]
> Why not just use start: 'now'?

You cant do `now + 50` or anything, so using now would always give the current time.

This change ties into the infinites-rewrite work I am doing, as 'now' is giving me some pain to figure out how to handle. An `insertAtPlayhead: boolean` option would make my life simpler there, but then core will need to predict the latency of playout, to minimise the risk of missing the start of the inserted piece. cc @nytamin

**Comment by thomasslee97** [comment]
No longer relevant, using `start: 'now'` works in the use cases we have

**Comment by Julusian** [comment]
I think that this is still a relevant issue, but it needs a more flexible fix so something to revisit in the future

**Pull request closed without merging**
