### PR TITLE
Feat: package management (for release 35)

### PR DESCRIPTION
**Pull request by nytamin**
This PR contains updates related to Package Manager that I've worked on during this sprint, to be merged into Release 35.

Things included in this PR:
* Changes to expectedPackages priorities
* Changes in the package-manager publication
* Rename collection "packageContainerStatuses" -> "packageContainerPackageStatuses"  because it was badly named before.
* Changed the methods exposed to Package Manager, to reduce the number of calls and process stuff in bulk.

* **Other information**:

**Status**

- [ ] Code documentation for the relevant parts in the code have been added/updated by the PR author
- [ ] The functionality has been tested by the PR author
- [ ] The functionality has been tested by NRK

### CODE REVIEW

**Review by sparkpunkd — APPROVED** [review]
Looks like a really good tidy and clean of the codebase and good alignment with the mono-repo design for server-core-integration. Approved.

The hack on line 175 of meteor/server/api/blueprints/context/context.ts to search by RegExp is accepted and we need to have a task in the future to look at doing better.

**Comment by jstarpl** [comment]
I think this should pull the changes made by @Julusian in PR #525

**Comment by jstarpl** [comment]
> The hack on line 175 of meteor/server/api/blueprints/context/context.ts to search by RegExp is accepted and we need to have a task in the future to look at doing better.

Specifically, the change allows removing the hack, see https://github.com/nrkno/tv-automation-server-core/commit/f6a681a4f419a73771cf92816ad3a5a3eec92f65

**Comment by Julusian** [comment]
> > The hack on line 175 of meteor/server/api/blueprints/context/context.ts to search by RegExp is accepted and we need to have a task in the future to look at doing better.
> 
> Specifically, the change allows removing the hack, see [f6a681a](https://github.com/nrkno/tv-automation-server-core/commit/f6a681a4f419a73771cf92816ad3a5a3eec92f65)

There's another hack in context.ts that I missed, and needs more thought on how to do properly. I wasnt sure how best to scope it to the segment/baseline/something that it should be limited to without making a mess. 
I have an idea, I am waiting to talk through it with Johan

**Comment by nytamin** [comment]
I agree, @jstarpl .
For the sake of progression, I'm going to revert the changes from PR #525 and merge in the changes from before that.
We'll continue the discussion and target the rest for the next release (36).

**Comment by nytamin** [comment]
@Julusian yeah let's have that discussion, and continue that implementation on the [feat/package-management](https://github.com/nrkno/tv-automation-server-core/tree/feat/package-management) branch (and possibly on the #525 PR).

**Pull request merged**
